/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datasafe_papl_Engine */

#ifndef _Included_com_datasafe_papl_Engine
#define _Included_com_datasafe_papl_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewRegoEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewRegoEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCloseRegoEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeCloseRegoEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddPolicy
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddPolicy
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddBundles
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddBundles
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddInput
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddInput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddInputJSON
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddInputJSON
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddData
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddStringData
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddStringData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddPolicyFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddPolicyFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoClearData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoClearData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoEvalQuery
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeRegoEvalQuery
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAddPolicy
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAddPolicy
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAddEntity
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAddEntity
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAuthorize
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAuthorize
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewStore
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewStore
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewMemoryStore
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewMemoryStore
  (JNIEnv *, jclass);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCloseStore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeCloseStore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeStoreSave
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeStoreSave
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeStoreGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeStoreGet
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeStoreGetVersion
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeStoreGetVersion
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeStoreGetVersionValue
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datasafe_papl_Engine_nativeStoreGetVersionValue
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeStoreDelete
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeStoreDelete
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewCedarEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewCedarEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCloseCedarEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeCloseCedarEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeAllKeysLE
 * Signature: (JJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datasafe_papl_Engine_nativeAllKeysLE
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeAllKeysBE
 * Signature: (JJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datasafe_papl_Engine_nativeAllKeysBE
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeAllKeysBEPageable
 * Signature: (JJJJ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_datasafe_papl_Engine_nativeAllKeysBEPageable
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeEvictLE
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeEvictLE
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeEvictBE
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeEvictBE
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
