/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_datasafe_papl_Engine */

#ifndef _Included_com_datasafe_papl_Engine
#define _Included_com_datasafe_papl_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewRegoEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewRegoEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCloseRegoEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeCloseRegoEngine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddPolicy
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddPolicy
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddBundles
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddBundles
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddInput
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddInput
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddInputJSON
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddInputJSON
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddData
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddStringData
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddStringData
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoAddPolicyFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoAddPolicyFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoClearData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_datasafe_papl_Engine_nativeRegoClearData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeRegoEvalQuery
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeRegoEvalQuery
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAddPolicy
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAddPolicy
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAddEntity
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAddEntity
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCedarAuthorize
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_datasafe_papl_Engine_nativeCedarAuthorize
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeNewCedarEngine
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeNewCedarEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_datasafe_papl_Engine
 * Method:    nativeCloseCedarEngine
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_datasafe_papl_Engine_nativeCloseCedarEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
